function [ h ] = my_drawArrow(x1,y1,x2,y2,headwidth,props)

h = annotation('arrow');
set(h,'parent', gca, ...
    'position', [x1,y1,x2-x1,y2-y1], ...
    'HeadLength', 10, 'HeadWidth', headwidth, 'HeadStyle', 'cback1', ...
    props{:} );
end